import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Feeds from '../components/Feeds'
import { useContext } from 'react'
import { AuthContext } from '../context/auth'
import { useRouter } from 'next/router'

export default function Home() {
  const { user } = useContext(AuthContext);
  const Redirect = () => {
    const router = useRouter();
    router.push('/login');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Reels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Welcome Motasim!</h1> */}
      { user?.uid? <Feeds/>: <Redirect/> }
    </div>
  )
}
